version: '3'
services:
  proxy:
    image: traefik
    restart: always
    networks:
      - net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
  portainer:
    image: portainer/portainer
    restart: always
    networks:
      - net
    labels:
      - traefik.backend=portainer
      - traefik.enable=true  
      - traefik.frontend.rule=Host:portainer.${TRAEFIK_DOMAIN}
      - traefik.port=9000    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_DIR}portainer:/data
  mysql:
    image: mysql:5.7.20
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    restart: always
    labels:
      - traefik.backend=adminer
      - traefik.enable=true
      - traefik.frontend.rule=Host:adminer.${TRAEFIK_DOMAIN}
      - traefik.port=8080
    networks:
      - net
  mongo:
    image: mongo:3.6
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mongo:/data/db
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}gitlab/data:/var/opt/gitlab
      - ${VOLUME_DIR}gitlab/config:/etc/gitlab
    labels:
      - traefik.backend=gitlab
      - traefik.enable=true
      - traefik.frontend.rule=Host:gitlab.${TRAEFIK_DOMAIN}
      - traefik.port=80
  directus:
    image: getdirectus/directus:6.4
    restart: always
    networks:
      - net
    environment:
      - DIRECTUS_DB_HOST=mysql
      - DIRECTUS_DB_PORT=3306
      - DIRECTUS_DB_SCHEMA=directus
      - DIRECTUS_DB_USER=root
      - DIRECTUS_DB_PASSWORD=
    labels:
      - traefik.backend=directus
      - traefik.enable=true
      - traefik.frontend.rule=Host:directus.${TRAEFIK_DOMAIN}
      - traefik.port=8080
networks:
  net: