version: '3'
services:
  mongo:
    image: mongo:3.5.13
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mongo:/data/db
    ports:
      - 27017:27017
  mysql:
    image: mysql:5.7.20
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  portainer:
    image: portainer/portainer
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net
networks:
  net: