version: '2'
services:
  oracle:
    build: .
    image: oracle/sqltools
    volumes:
      - ${DATA_DIR}:/var/opt
    environment:
      - DD_BASE_DIR=/var/opt
      - DD_MUPR0_USR_APP=MUPR_OWN
      - DD_MUPR0_PWD_APP=MUPR_OWN
      - DD_MUPR0_SID=//10.24.216.117:1555/CAPGEMINI
