version: '3'
services:
  proxy:
    image: traefik
    restart: always
    networks:
      - net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
  mongo:
    image: mongo:3.5.13
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mongo:/data/db
    ports:
      - 27017:27017
  mysql:
    image: mysql:5.7.20
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  portainer:
    image: portainer/portainer
    restart: always
    networks:
      - net
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.localhost
      - traefik.enable=true  
      - traefik.port=9000    
    volumes:
      - ${VOLUME_DIR}portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  adminer:
    image: adminer
    restart: always
    labels:
      - traefik.backend=adminer
      - traefik.frontend.rule=Host:adminer.localhost
      - traefik.enable=true
      - traefik.port=8080
    networks:
      - net
networks:
  net: