version: '3'
services:
  proxy:
    image: traefik
    restart: always
    networks:
      - net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
  portainer:
    image: portainer/portainer
    restart: always
    networks:
      - net
    labels:
      - traefik.backend=portainer
      - traefik.enable=true  
      - traefik.port=9000    
    volumes:
      - ${VOLUME_DIR}portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  net: