version: '3'
services:
  wp:
    image: seven782/wordpress
    build: .
    container_name: wp_${SITE}
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}${SITE}:/var/www/html
    labels:
      - traefik.backend=wp_${SITE}
      - traefik.enable=true  
networks:
  net: