version: '3'
services:
  jenkins:
    image: jenkins
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}jenkins:/var/jenkins_home
    labels:
      - traefik.backend=jenkins
      - traefik.enable=true
      - traefik.port=8080
    networks:
      - net
networks:
  net: