version: '3.4'
services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9999:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_DIR}portainer:/data