version: '3'
services:
  mysql:
    image: mysql:5.7.20
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    restart: always
    labels:
      - traefik.backend=adminer
      - traefik.enable=true
      - traefik.frontend.rule=Host:adminer.${TRAEFIK_DOMAIN}
      - traefik.port=8080
    networks:
      - net
networks:
  net: