version: '3.4'
services:
  php:
    build: ./build
    image: php-custom:5.6.32-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${VOLUME_DIR}php:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache2:/etc/apache2/sites-enabled
    environment:
      - XDEBUG_CONFIG=remote_host=${IP}
    depends_on:
      - mysql
      - mongo
  mysql:
    image: mysql:5.7.20
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${VOLUME_DIR}mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  mongo:
    image: mongo:3.5.13
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${VOLUME_DIR}mongo:/data/db
