version: '3'
services:
  php:
    image: seven782/pxmm
    build: .
    container_name: php_${SITE}
    restart: always
    networks:
      - net
    volumes:
      - ${VOLUME_DIR}${SITE}:/var/www/html
    labels:
      - traefik.backend=php_${SITE}
      - traefik.enable=true  
networks:
  net: